version: '3'
services:
  flyway:
    image: flyway/flyway:10.10
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    environment:
      FLYWAY_URL: "jdbc:postgresql://postgres:5432/test"
      FLYWAY_USER: "postgres"
      FLYWAY_PASSWORD: "password"
    volumes:
      - ${PWD}/sql:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=test
